spring:
  main:
    log-startup-info: false
    banner-mode: off

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:mem:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password

server:
  port: 8080

logging:
  level:
    ru.yandex.practicum.filmorate: DEBUG
    org:
      zalando:
        logbook: TRACE
